baseURL: https://junghoon-vans.github.io/
title: Vanslog
theme: papermod
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: UA-186109814-1
defaultContentLanguage: ko

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"