[ko]
  title = "Jeonghun's blog"
  languageName = "한국어"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/ko"
  
[en]
  title = "Jeonghun's blog"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"