main:
  - name: 아카이브
    url: archives/
    weight: 1
  - name: 태그
    url: tags/
    weight: 2
  - name: 카테고리
    url: categories/
    weight: 3
  - name: 시리즈
    url: series/
    weight: 4
  - name: 검색
    url: search/
    weight: 5
  - name: TIL
    url: https://til.vanslog.io
    weight: 6
