[[main]]
  identifier = "about"
  name = "📖 About"
  url = "/about/"
  weight = 1

[[main]]
  identifier = "resume"
  name = "👨‍💻 Resume"
  url = "/resume/"
  weight = 2

[[main]]
  identifier = "posts"
  name = "📝 Posts"
  url = "/posts/"
  weight = 3

[[main]]
  identifier = "tils"
  name = "🔥 TIL"
  url = "/TIL/docs/"
  weight = 4
