baseURL = "http://Jeonghun-Ban.github.io"
languageCode = "ko-kr"
title = "Jeonghun-Ban"
theme = "docsy"

defaultContentLanguage = "ko"

[languages.ko]
time_format_default = "2006.01.02"
time_format_blog = "2006.01.02"

[params]
copyright_website = "Jeonghun-Ban"

# Enable Lunr.js offline search
offlineSearch = true

[params.links]
# Social relevant links.
[[params.links.social]]
	name = "Facebook"
	url = "https://www.facebook.com/profile.php?id=100008030658971"
	icon = "fab fa-facebook"

[[params.links.social]]
	name = "Instagram"
	url = "https://www.instagram.com/bj_h00n/"
	icon = "fab fa-instagram"

[[params.links.social]]
	name = "LinkedIn"
	url = "https://www.linkedin.com/in/%EC%A0%95%ED%9B%88-%EB%B0%98-81683b17a/"
	icon = "fab fa-linkedin"

# Developer relevant links.
[[params.links.developer]]
	name = "Rocket Punch"
	url = "https://www.rocketpunch.com/@sae-yujeo-cugab062fb66"
	icon = "fas fa-rocket"
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/Jeonghun-Ban"
	icon = "fab fa-github"

[[params.links.developer]]
	name = "Contact"
	url = "mailto://junghoon.ban@gmail.com"
	icon = "fa fa-envelope"

    