name: Build & Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout blog source
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: npm install
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15.3.0'
      - run: npm install

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PRIVATE_DEPLOY_KEY }}
          external_repository: Jeonghun-Ban/Jeonghun-Ban.github.io
          publish_branch: main
          publish_dir: ./public
